name: data
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Flat Data
        uses: githubocto/flat@v3.4.0
        with:
          http_url: data-api.binance.vision/api/v3/uiKlines?symbol=ETHBTC&interval=1m&limit=60
          downloaded_filename: ethbtc.txt
      - name: Flat Data
        uses: githubocto/flat@v3.4.0
        with:
          http_url: data-api.binance.vision/api/v3/uiKlines?symbol=BTCUSDT&interval=1m&limit=60
          downloaded_filename: btcusdt.txt
      - name: Flat Data
        uses: githubocto/flat@v3.4.0
        with:
          http_url: data-api.binance.vision/api/v3/uiKlines?symbol=ETHUSDT&interval=1m&limit=5
          downloaded_filename: ethusdt.txt
