name: Flat
on:
  push:
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch: null
  schedule:
    - cron: "*/5 * * * *"
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: data-api.binance.vision/api/v3/uiKlines?symbol=ETHBTC&interval=1m&limit=60
          downloaded_filename: eth-btc-price.json
